# Generated by Django 3.2.6 on 2021-10-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=128, verbose_name='langs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk_id',
            field=models.CharField(default='id00000000', max_length=128, verbose_name='vk_id'),
        ),
    ]
